[package]
name = "campfire_views"
version = "0.1.0"
edition.workspace = true

[dependencies]
askama = { workspace = true, features = ["blocks"] }
campfire_routes.workspace = true
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
html5ever.workspace = true

[lints]
workspace = true
