//! Golden-vector tests against `vectors/rails_compat.json` (generated by the reference app with
//! `reference-tools/rails_compat_vectors.rb`). The last test also writes what Rust generates to
//! `target/rails_compat_rust_output.json`, which `reference-tools/rails_compat_verify_rust.rb`
//! checks with Rails itself.
use std::path::PathBuf;
use std::sync::LazyLock;

use jiff::Timestamp;
use serde_json::{Value, json};

use crate::global_id::{self, GlobalId};
use crate::metadata::{self, Serializer};
use crate::{Secrets, cookies, password, signed_id, turbo};

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

static VECTORS: LazyLock<Value> = LazyLock::new(|| {
    let path = workspace_root().join("vectors/rails_compat.json");
    serde_json::from_str(&std::fs::read_to_string(&path).expect("vectors/rails_compat.json")).expect("valid JSON")
});

static SECRETS: LazyLock<Secrets> = LazyLock::new(|| Secrets::new(str(&VECTORS["secret_key_base"])));

fn v(path: &str) -> &'static Value {
    path.split('.').fold(&*VECTORS, |value, key| &value[key])
}

fn cases(path: &str) -> &'static Vec<Value> {
    v(path).as_array().unwrap_or_else(|| panic!("{path} is an array"))
}

fn str(value: &Value) -> &str {
    value.as_str().unwrap_or_else(|| panic!("expected a string, got {value}"))
}

fn opt_str(value: &Value) -> Option<&str> {
    value.as_str()
}

fn time(value: &Value) -> Timestamp {
    str(value).parse().unwrap()
}

fn opt_time(value: &Value) -> Option<Timestamp> {
    opt_str(value).map(|s| s.parse().unwrap())
}

fn now() -> Timestamp {
    time(v("now"))
}

fn label(case: &Value) -> String {
    format!("case {:?}", case["case"].as_str().unwrap_or(""))
}

#[test]
fn key_generator() {
    for case in cases("key_generator") {
        let key = SECRETS
            .key_generator
            .generate_key(str(&case["salt"]), case["length"].as_u64().unwrap() as usize);
        assert_eq!(hex::encode(key), str(&case["key_hex"]), "salt {}", case["salt"]);
    }
}

#[test]
fn cookie_escaping() {
    for case in cases("cookie_escaping") {
        if let Some(raw) = opt_str(&case["raw"]) {
            assert_eq!(cookies::escape(raw), str(&case["wire"]), "escape {raw:?}");
        }
        assert_eq!(
            cookies::unescape(str(&case["wire"])),
            str(&case["parsed"]),
            "unescape {}",
            case["wire"]
        );
    }
}

#[test]
fn signed_cookies_are_generated_byte_for_byte() {
    for case in cases("signed_cookies.generate") {
        let raw = cookies::sign(&SECRETS, str(&case["name"]), str(&case["value"]), opt_time(&case["expires_at"]));
        assert_eq!(raw, str(&case["raw"]), "value {}", case["value"]);
        let wire = str(&case["set_cookie"]).split(';').next().unwrap().split_once('=').unwrap().1;
        assert_eq!(cookies::escape(&raw), wire);
    }
}

#[test]
fn permanent_cookies_expire_in_twenty_years() {
    let session_token = &cases("signed_cookies.generate")[0];
    assert_eq!(cookies::permanent_expires_at(now()), time(&session_token["expires_at"]));
}

#[test]
fn signed_cookies_verify_like_rails() {
    for case in cases("signed_cookies.verify") {
        let value = cookies::verify_signed_value(&SECRETS, str(&case["name"]), str(&case["raw"]), time(&case["now"]));
        assert_eq!(value.unwrap_or(Value::Null), case["expected"], "{}", label(case));
        let string = cookies::verify_signed(&SECRETS, str(&case["name"]), str(&case["raw"]), time(&case["now"]));
        assert_eq!(string.as_deref(), case["expected"].as_str(), "{}", label(case));
    }
}

#[test]
fn encrypted_cookies_decrypt_like_rails() {
    for case in cases("encrypted_cookies.verify") {
        let value = cookies::decrypt(&SECRETS, str(&case["name"]), str(&case["raw"]), time(&case["now"]));
        assert_eq!(value.unwrap_or(Value::Null), case["expected"], "{}", label(case));
    }
}

#[test]
fn encrypted_cookie_plaintext_matches_rails() {
    let encryptor = cookies::encrypted_cookie_encryptor(&SECRETS);
    for case in cases("encrypted_cookies.generate") {
        let plaintext = encryptor.decrypt(str(&case["raw"])).expect("decrypts");
        assert_eq!(String::from_utf8(plaintext).unwrap(), str(&case["plaintext"]));

        // With serde_json's preserve_order (on workspace-wide), Rust's plaintext is byte-identical.
        let ours = metadata::serialize_with_metadata(
            Serializer::Null,
            &Value::String(crate::json::encode(&case["value"])),
            Some(&format!("cookie.{}", str(&case["name"]))),
            opt_time(&case["expires_at"]),
        );
        assert_eq!(String::from_utf8(ours).unwrap(), str(&case["plaintext"]));

        let raw = cookies::encrypt(&SECRETS, str(&case["name"]), &case["value"], opt_time(&case["expires_at"]));
        assert_eq!(
            cookies::decrypt(&SECRETS, str(&case["name"]), &raw, now()),
            Some(case["value"].clone())
        );
    }
}

#[test]
fn rails_session_and_its_forms_are_accepted() {
    let session = v("session");
    assert_eq!(session["post_with_form_token_status"], 302);
    assert_eq!(session["post_with_bad_token_status"], 422);

    let hash = cookies::decrypt(&SECRETS, "_campfire_session", str(&session["session_cookie_raw"]), now()).unwrap();
    assert_eq!(hash, session["session"]);

    let token = str(&session["session_token_value"]);
    assert_eq!(
        cookies::verify_signed(&SECRETS, "session_token", str(&session["session_token_raw"]), now()).as_deref(),
        Some(token)
    );
    let ours = cookies::sign(&SECRETS, "session_token", token, Some(cookies::permanent_expires_at(now())));
    assert_eq!(ours, str(&session["session_token_raw"]));
}

#[test]
fn signed_ids() {
    for case in cases("signed_ids.generate") {
        let model = str(&case["model"]);
        let generated = signed_id::generate(
            &SECRETS,
            model,
            case["id"].as_i64().unwrap(),
            opt_str(&case["purpose"]),
            opt_time(&case["expires_at"]),
        );
        assert_eq!(generated, str(&case["signed_id"]), "{model} {} {}", case["id"], case["purpose"]);
    }
    for case in cases("signed_ids.verify") {
        let id = signed_id::verify(
            &SECRETS,
            str(&case["model"]),
            str(&case["signed_id"]),
            opt_str(&case["purpose"]),
            time(&case["now"]),
        );
        let expected = match &case["expected"] {
            Value::String(s) => Some(s.parse().unwrap()),
            other => other.as_i64(),
        };
        assert_eq!(id, expected, "{}", label(case));
    }
}

#[test]
fn global_ids() {
    for case in cases("global_ids") {
        let gid = GlobalId::parse(str(&case["gid"])).unwrap();
        assert_eq!(gid, GlobalId::new(str(&case["model_name"]), str(&case["id"])));
        assert_eq!(gid.to_string(), str(&case["gid"]));
        assert_eq!(gid.to_param(), str(&case["param"]));
    }
}

#[test]
fn sgids() {
    assert_eq!(v("sgids.app"), global_id::APP);
    for case in cases("sgids.generate") {
        let gid = GlobalId::parse(str(&case["gid"])).unwrap();
        let data = str(&case["data"]);
        let generated = if data.ends_with("?expires_in") {
            assert_eq!(str(&case["purpose"]), global_id::ATTACHABLE_PURPOSE);
            global_id::attachable_sgid(&SECRETS, &gid)
        } else {
            global_id::sgid(&SECRETS, &gid, str(&case["purpose"]), opt_time(&case["expires_at"]))
        };
        assert_eq!(generated, str(&case["sgid"]), "{data} for {}", case["purpose"]);
    }
    for case in cases("sgids.verify") {
        let located = global_id::locate_signed(&SECRETS, str(&case["sgid"]), str(&case["purpose"]), time(&case["now"]));
        assert_eq!(located, opt_str(&case["expected"]).and_then(GlobalId::parse), "{}", label(case));
    }
}

#[test]
fn unverified_sgids_only_yield_users() {
    let existing_user_ids = ["1", "2"];
    for case in cases("unverified_sgids") {
        let result = global_id::unverified_attachable_user(opt_str(&case["sgid"]));
        // Rails also looks the user up; a missing one is nil.
        let found = result
            .clone()
            .map(|gid| gid.filter(|gid| existing_user_ids.contains(&gid.id.as_str())));
        match &case["expected"] {
            Value::Null => assert_eq!(found, Ok(None), "{}", label(case)),
            Value::String(gid) => {
                let expected = GlobalId::parse(gid).unwrap();
                let found = found.unwrap().unwrap_or_else(|| panic!("{} found nothing", label(case)));
                assert_eq!((found.model_name, found.id), (expected.model_name, expected.id), "{}", label(case));
            }
            raises => assert!(result.is_err(), "{} should fail like Rails ({raises})", label(case)),
        }
    }
}

#[test]
fn tampered_sgids_for_other_models_are_rejected() {
    // Independent of the oracle: the signature-ignoring fallback must never yield a non-User.
    for model in ["Rooms::Open", "Account", "Message", "Rooms::Direct", "Session"] {
        let gid = GlobalId::new(model, 1);
        let forged = global_id::verifier(&Secrets::new("attacker")).generate(&Value::String(gid.to_string()), Some("attachable"), None);
        assert_eq!(global_id::unverified_attachable_user(Some(&forged)), Ok(None));
        assert_eq!(global_id::locate_signed(&SECRETS, &forged, "attachable", now()), None);
    }
}

#[test]
fn turbo_stream_names() {
    for case in cases("turbo_stream_names.generate") {
        let parts: Vec<&str> = case["parts"].as_array().unwrap().iter().map(str).collect();
        assert_eq!(parts.join(":"), str(&case["stream_name"]));
        assert_eq!(turbo::signed_stream_name(&SECRETS, &parts), str(&case["signed"]));
    }
    for case in cases("turbo_stream_names.verify") {
        let name = turbo::verified_stream_name(&SECRETS, str(&case["signed"]));
        let expected = match &case["expected"] {
            Value::Null => None,
            Value::String(s) => Some(s.clone()),
            other => Some(other.to_string()),
        };
        assert_eq!(name, expected, "{}", label(case));
    }
}

#[test]
fn app_verifiers() {
    for case in cases("app_verifiers.generate") {
        let verifier = crate::app_verifier(&SECRETS, str(&case["name"]));
        let message = verifier.generate_raw(str(&case["data_json"]), opt_str(&case["purpose"]), opt_time(&case["expires_at"]));
        assert_eq!(message, str(&case["message"]), "{} {}", case["name"], case["data_json"]);
    }
    for case in cases("app_verifiers.verify") {
        let verifier = crate::app_verifier(&SECRETS, str(&case["name"]));
        let data = verifier
            .verify_raw(str(&case["message"]), opt_str(&case["purpose"]), time(&case["now"]))
            .ok();
        assert_eq!(data.as_deref(), opt_str(&case["expected_json"]), "{}", label(case));
    }
}

#[test]
fn passwords() {
    assert_eq!(v("passwords.cost"), password::COST);
    for case in cases("passwords.digests") {
        assert!(str(&case["digest"]).starts_with("$2a$12$"));
    }
    // Cost 12 takes a while per check, so run them side by side.
    std::thread::scope(|scope| {
        for case in cases("passwords.checks") {
            scope.spawn(move || {
                let ok = password::verify(str(&case["password"]), str(&case["digest"]));
                assert_eq!(
                    Value::Bool(ok),
                    case["expected"],
                    "{:?} against {}",
                    case["password"],
                    case["digest"]
                );
            });
        }
    });
    assert!(password::verify("secret123456", str(v("passwords.seeded_user_digest"))));
    let ours = password::digest_with_cost("pässwörd ☃", password::MIN_COST);
    assert!(ours.starts_with("$2a$04$") && password::verify("pässwörd ☃", &ours));
    assert!(!password::verify("anything", "not a digest"));
}

/// Writes Rust-generated values for `reference-tools/rails_compat_verify_rust.rb`.
#[test]
fn write_rust_output_for_rails_to_verify() {
    let now = now();
    let permanent = cookies::permanent_expires_at(now);
    let secrets = &*SECRETS;

    let signed_cookies: Vec<Value> = ["token-from-rust", "with space+plus/slash=", "<é&☃>", ""]
        .iter()
        .map(|value| json!({ "name": "session_token", "value": value, "raw": cookies::sign(secrets, "session_token", value, Some(permanent)) }))
        .chain(std::iter::once(json!({ "name": "other", "value": "no expiry", "raw": cookies::sign(secrets, "other", "no expiry", None) })))
        .collect();

    let encrypted_cookies: Vec<Value> = [
        json!({ "session_id": "rust-session-id", "return_to_after_authenticating": "/rooms/1" }),
        json!({ "return_to_after_authenticating": "http://campfire.test/rooms/1?a=1&b=<2>", "n": 1 }),
        json!("plain"),
        json!([1, null, "☃\u{2028}"]),
    ]
    .into_iter()
    .map(|value| json!({ "name": "_campfire_session", "raw": cookies::encrypt(secrets, "_campfire_session", &value, Some(permanent)), "value": value }))
    .collect();

    let session_token = "RustMadeSessionToken1234";

    let four_hours = now.checked_add(jiff::SignedDuration::from_hours(4)).unwrap();
    let signed_ids: Vec<Value> = [(1, Some("avatar"), None), (2, Some("transfer"), Some(four_hours)), (12345, None, None), (9_007_199_254_740_993, Some("avatar"), None)]
        .iter()
        .map(|(id, purpose, expires_at)| json!({ "model": "User", "id": id, "purpose": purpose, "signed_id": signed_id::generate(secrets, "User", *id, *purpose, *expires_at) }))
        .collect();

    let an_hour = now.checked_add(jiff::SignedDuration::from_hours(1)).unwrap();
    let sgids = vec![
        json!({ "sgid": global_id::attachable_sgid(secrets, &GlobalId::new("User", 1)), "purpose": "attachable", "expected": "gid://campfire/User/1?expires_in" }),
        json!({ "sgid": global_id::attachable_sgid(secrets, &GlobalId::new("User", 2)), "purpose": "attachable", "expected": "gid://campfire/User/2?expires_in" }),
        json!({ "sgid": global_id::sgid(secrets, &GlobalId::new("User", 1), "attachable", Some(an_hour)), "purpose": "attachable", "expected": "gid://campfire/User/1" }),
        json!({ "sgid": global_id::sgid(secrets, &GlobalId::new("Rooms::Open", 1), "default", None), "purpose": "attachable", "expected": null }),
    ];

    let room = GlobalId::new("Rooms::Open", 1).to_param();
    let user = GlobalId::new("User", 1).to_param();
    let turbo: Vec<Value> = [
        vec![room.as_str(), "messages"],
        vec!["rooms"],
        vec![user.as_str(), "rooms"],
        vec!["unicode ☃ <&>"],
    ]
    .iter()
    .map(|parts| json!({ "signed": turbo::signed_stream_name(secrets, parts), "expected": parts.join(":") }))
    .collect();

    let passwords: Vec<Value> = [
        ("secret123456", password::COST),
        ("pässwörd ☃", password::MIN_COST),
        (&"a".repeat(80), password::MIN_COST),
    ]
    .iter()
    .map(|(pw, cost)| json!({ "password": pw, "digest": password::digest_with_cost(pw, *cost) }))
    .collect();

    let app_verifiers: Vec<Value> = [
        (
            r#"{"key":"k1","disposition":"inline; filename=\"a\u0026b.png\"","content_type":"image/png","service_name":"local"}"#,
            Some("blob_key"),
            Some(four_hours),
        ),
        ("42", Some("blob_id"), None),
        (r#"{"z":1,"a":2}"#, Some("x"), None),
    ]
    .iter()
    .map(|(data_json, purpose, expires_at)| {
        json!({ "name": "ActiveStorage", "data_json": data_json, "purpose": purpose,
                "message": crate::app_verifier(secrets, "ActiveStorage").generate_raw(data_json, *purpose, *expires_at) })
    })
    .collect();

    let output = json!({
        "app_verifiers": app_verifiers,
        "now": v("now"),
        "signed_cookies": signed_cookies,
        "encrypted_cookies": encrypted_cookies,
        "session": { "session_token": session_token,
                     "session_token_cookie": cookies::sign(secrets, "session_token", session_token, Some(permanent)) },
        "signed_ids": signed_ids,
        "sgids": sgids,
        "turbo_stream_names": turbo,
        "passwords": passwords,
    });

    let path = workspace_root().join("target/rails_compat_rust_output.json");
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, serde_json::to_string_pretty(&output).unwrap() + "\n").unwrap();
}
